[
    {"thai":"กิน","romanization":"gin","english":"to eat"},
    {"thai":"ด้วย","romanization":"dûay","english":"too"},
    {"thai":"ดื่ม","romanization":"dʉ̀ʉm","english":"to drink"},
    {"thai":"เดิน","romanization":"dəən","english":"to walk"},
    {"thai":"วิ่ง","romanization":"wîng","english":"to run"},
    {"thai":"พูด","romanization":"pûut","english":"to talk"},
    {"thai":"นั่ง","romanization":"nâng","english":"to sit"},
    {"thai":"ยืน","romanization":"yʉʉn","english":"to stand"},
    {"thai":"นอน","romanization":"non","english":"to sleep"},
    {"thai":"กระโดด","romanization":"kra-dod","english":"to jump"},
    {"thai":"ฟัง","romanization":"fang","english":"to listen"},
    {"thai":"อ่าน","romanization":"àan","english":"to read"},
    {"thai":"เขียน","romanization":"kǐan","english":"to write"},
    {"thai":"ร้องไห้","romanization":"rlong-hai","english":"to cry"},
    {"thai":"หัวเราะ","romanization":"huua-rloh","english":"to laugh"},
    {"thai":"ยิ้ม","romanization":"yímm","english":"to smile"},
    {"thai":"ทำ","romanization":"tam","english":"to do / to make"},
    {"thai":"ทำงาน","romanization":"tam-ngaan","english":"work"},
    {"thai":"รัก","romanization":"rák","english":"to love"},
    {"thai":"ลืม","romanization":"lʉʉm","english":"to forget"},
    {"thai":"จำ","romanization":"jamm","english":"to remember"},
    {"thai":"ให้","romanization":"hâi","english":"to give"},
    {"thai":"แล้ว","romanization":"léaw","english":"already"},
    {"thai":"ยังไม่","romanization":"yang-mâi","english":"not yet"},
    {"thai":"ใช้","romanization":"chái","english":"to use"},
    {"thai":"ทำ","romanization":"tham","english":"to do"},
    {"thai":"ไป","romanization":"bpai","english":"to go"},
    {"thai":"มา","romanization":"maa","english":"to come"},
    {"thai":"หัวเราะ","romanization":"hǔua-ráw","english":"to laugh"},
    {"thai":"เห็น","romanization":"hěn","english":"to see"},
    {"thai":"ไกล","romanization":"glai","english":"far"},
    {"thai":"เล็ก","romanization":"lék","english":"small"},
    {"thai":"กลาง","romanization":"glang","english":"medium"},
    {"thai":"ใหญ่","romanization":"yài","english":"large"},
    {"thai":"ดี","romanization":"dii","english":"good"},
    {"thai":"สวย","romanization":"sǔuai","english":"beautiful"},
    {"thai":"น่าเกลียด","romanization":"nâa-glìiat","english":"ugly"},
    {"thai":"ยาก","romanization":"yâak","english":"difficult"},
    {"thai":"ง่าย","romanization":"ngâai","english":"easy"},
    {"thai":"ไม่ดี","romanization":"mâi-dii","english":"bad"},
    {"thai":"ใกล้","romanization":"glâi","english":"near"},
    {"thai":"กาแฟ","romanization":"gaa-faae","english":"coffee"},
    {"thai":"เบียร์","romanization":"biia","english":"beer"},
    {"thai":"ชา","romanization":"chaa","english":"tea"},
    {"thai":"ไวน์","romanization":"waai","english":"wine"},
    {"thai":"น้ำ","romanization":"náam","english":"water"},
    {"thai":"เนื้อวัว","romanization":"núuea-wuua","english":"beef"},
    {"thai":"เนื้อหมู","romanization":"núuea-mǔu","english":"pork"},
    {"thai":"ไก่","romanization":"gài","english":"chicken"},
    {"thai":"เนื้อลูกแกะ","romanization":"núuea-lûuk-gàe","english":"lamb"},
    {"thai":"ปลา","romanization":"bplaa","english":"fish"},
    {"thai":"เท้า","romanization":"tháao","english":"foot"},
    {"thai":"ขา","romanization":"khǎa","english":"leg"},
    {"thai":"หัว","romanization":"hǔua","english":"head"},
    {"thai":"แขน","romanization":"khǎaen","english":"arm"},
    {"thai":"มือ","romanization":"muue","english":"hand"},
    {"thai":"นิ้วมือ","romanization":"níu-muue","english":"finger"},
    {"thai":"ร่างกาย","romanization":"râang-gaai","english":"body"},
    {"thai":"ท้อง","romanization":"tháawng","english":"stomach"},
    {"thai":"หลัง","romanization":"lǎng","english":"back"},
    {"thai":"หน้าอก","romanization":"nâa-òk","english":"chest"},
    {"thai":"หมอ","romanization":"mǎaw","english":"doctor"},
    {"thai":"ครู","romanization":"khruu","english":"teacher"}
]
