[
    {"thai":"ขาย", "english":"to sell"},
    {"thai":"ขายของ", "english":"to make a sale"},
    {"thai":"สีขาว", "english":"white"},
    {"thai":"ไฟฉาย", "english":"flashlight"},
    {"thai":"ถาม", "english":"to ask"},
    {"thai":"คำถาม", "english":"question"},
    {"thai":"สาม", "english":"three"},
    {"thai":"สาย", "english":"to be late, string"},
    {"thai":"สายไฟ", "english":"wire"},
    {"thai":"หาย", "english":"lost, healed"},
    {"thai":"หาว", "english":"yawn"},
    {"thai":"สูง", "english":"tall"},
    {"thai":"แขน", "english":"arm"},
    {"thai":"แถม", "english":"give something extra"},
    {"thai":"ของแถม", "english":"giveaway"},
    {"thai":"แถว", "english":"row, area"},
    {"thai":"แผน", "english":"plan"},
    {"thai":"แสง", "english":"light (ray)"},
    {"thai":"แสน", "english":"one hundred thousand"},
    {"thai":"โขน", "english":"Ramayana drama play"},
    {"thai":"โสม", "english":"ginseng"},
    {"thai":"โหน", "english":"to hang, swing"},
    {"thai":"ของ", "english":"object, of (belonging to)"},
    {"thai":"ถอน", "english":"pluck, withdraw"},
    {"thai":"ถอย", "english":"retreat, fall"},
    {"thai":"ผอม", "english":"thin"},
    {"thai":"สอง", "english":"two"},
    {"thai":"สอน", "english":"to teach"},
    {"thai":"หอน", "english":"to howl"},
    {"thai":"หอม", "english":"pleasant-smelling"},
    {"thai":"หอย", "english":"shellfish"},
    {"thai":"เขย", "english":"male in-law"},
    {"thai":"เฉย", "english":"quietly, calm"},
    {"thai":"เขียน", "english":"to write"},
    {"thai":"สีเขียว", "english":"green"},
    {"thai":"เฉียง", "english":"oblique, slant"},
    {"thai":"เถียง", "english":"argue"},
    {"thai":"เสียง", "english":"sound, voice"},
    {"thai":"สวน", "english":"park, garden"},
    {"thai":"สวย", "english":"beautiful"},
    {"thai":"หวง", "english":"possessive, clingy"},
    {"thai":"หวย", "english":"lottery"}
]
