[
    {"thai":"คาง", "english":"chin"},
    {"thai":"ชาม", "english":"bowl, dish"},
    {"thai":"ชาย", "english":"man, male"},
    {"thai":"ทาง", "english":"way"},
    {"thai":"ทาน", "english":"to eat"},
    {"thai":"ทาย", "english":"to guess"},
    {"thai":"นาง", "english":"Mrs."},
    {"thai":"นางสาว", "english":"Miss"},
    {"thai":"นาย", "english":"Mr."},
    {"thai":"นาน", "english":"long time"},
    {"thai":"พาน", "english":"tray (for monks)"},
    {"thai":"พาย", "english":"to paddle, to row, pie"},
    {"thai":"ฟาง", "english":"rice straw"},
    {"thai":"ยาง", "english":"tire, rubber"},
    {"thai":"ยาม", "english":"security guard"},
    {"thai":"ยาย", "english":"grandmother (mother's side)"},
    {"thai":"ยาว", "english":"lengthy"},
    {"thai":"ราง", "english":"rail, track"},
    {"thai":"ลาง", "english":"omen, some"},
    {"thai":"ลาน", "english":"yard, playground"},
    {"thai":"ลาย", "english":"stripes, design, pattern"},
    {"thai":"ลาว", "english":"Lao (country)"},
    {"thai":"วาง", "english":"to set down"},
    {"thai":"งาน", "english":"job, task"},
    {"thai":"ทำงาน", "english":"to work"},
    {"thai":"คืน", "english":"night, to return"},
    {"thai":"ฟืน", "english":"firewood"},
    {"thai":"ยืน", "english":"to stand up"},
    {"thai":"ยืม", "english":"to borrow"},
    {"thai":"ลืม", "english":"to forget"},
    {"thai":"แมว", "english":"cat"},
    {"thai":"แซง", "english":"to overtake"},
    {"thai":"แทง", "english":"to stab, knife"},
    {"thai":"แพง", "english":"expensive"},
    {"thai":"กำแพง", "english":"wall"},
    {"thai":"แฟน", "english":"significant other"},
    {"thai":"แรง", "english":"strength, intensive"},
    {"thai":"แทน", "english":"instead, to replace"},
    {"thai":"แยม", "english":"jam (jelly)"},
    {"thai":"โยน", "english":"to throw"},
    {"thai":"โรง", "english":"building"},
    {"thai":"โรงเรียน", "english":"school"},
    {"thai":"โรงแรม", "english":"hotel"},
    {"thai":"โรงงาน", "english":"factory"},
    {"thai":"โรย", "english":"to sprinkle, to scatter"},
    {"thai":"โลง", "english":"coffin"},
    {"thai":"คอย", "english":"keep on (doing something), await"},
    {"thai":"ซอง", "english":"envelope, package"},
    {"thai":"ซอย", "english":"soi (road)"},
    {"thai":"ทอง", "english":"gold"},
    {"thai":"ทอม", "english":"lesbian (tomboy)"},
    {"thai":"นอน", "english":"to sleep (lie down)"},
    {"thai":"ฟอง", "english":"bubble, foam"},
    {"thai":"มอง", "english":"to look at"},
    {"thai":"ยอม", "english":"to let, to agree (reluctantly)"},
    {"thai":"รอย", "english":"trail, mark"},
    {"thai":"ลอง", "english":"to try (sample)"},
    {"thai":"ลอย", "english":"to float"},
    {"thai":"เคย", "english":"once, ever"},
    {"thai":"เงิน", "english":"money"},
    {"thai":"เงย", "english":"to look up, to raise one's head"},
    {"thai":"เนย", "english":"butter"},
    {"thai":"เพิง", "english":"shed"},
    {"thai":"เมิน", "english":"to look away, ignore"},
    {"thai":"เลย", "english":"so much, to pass, go through"},
    {"thai":"เชย", "english":"old-fashioned"},
    {"thai":"เทียน", "english":"candle"},
    {"thai":"เทียม", "english":"artificial"},
    {"thai":"เพียง", "english":"only"},
    {"thai":"เรียง", "english":"to arrange"},
    {"thai":"เรียน", "english":"to learn"},
    {"thai":"เมือง", "english":"city"},
    {"thai":"เยือน", "english":"to visit"},
    {"thai":"ควง", "english":"screw, to twirl, to go on a date"},
    {"thai":"งวง", "english":"elephant trunk"},
    {"thai":"ชวน", "english":"to persuade"},
    {"thai":"ซวย", "english":"to be unlucky"},
    {"thai":"ทวง", "english":"to demand"},
    {"thai":"ทวน", "english":"to move against"},
    {"thai":"พวง", "english":"cluster, bunch"},
    {"thai":"รวม", "english":"to combine, include"},
    {"thai":"รวย", "english":"wealthy"},
    {"thai":"นวม", "english":"boxing glove"}
]
