[
    {"thai":"กางเกง","romanization":"","english":"trousers"},
    {"thai":"กาว","romanization":"","english":"glue"},
    {"thai":"จาน","romanization":"","english":"plate"},
    {"thai":"จาม","romanization":"","english":"to sneeze"},
    {"thai":"ดาว","romanization":"","english":"star"},
    {"thai":"ตาม","romanization":"","english":"to follow"},
    {"thai":"ตาย","romanization":"","english":"dead"},
    {"thai":"บาง","romanization":"","english":"thin (for things), some"},
    {"thai":"บางครั้ง","romanization":"","english":"sometimes"},
    {"thai":"อาย","romanization":"","english":"shy"},
    {"thai":"จีน","romanization":"","english":"China"},
    {"thai":"ปีน","romanization":"","english":"to climb"},
    {"thai":"ปืน","romanization":"","english":"gun"},
    {"thai":"จูง","romanization":"","english":"to lead (by the hand)"},
    {"thai":"จูงมือ","romanization":"","english":"to lead (someone) by the hand"},
    {"thai":"เอง","romanization":"","english":"only, just (by oneself)"},
    {"thai":"ตัวเอง","romanization":"","english":"oneself, ourselves"},
    {"thai":"สีแดง","romanization":"","english":"red"},
    {"thai":"แตง","romanization":"","english":"melon"},
    {"thai":"แตงโม","romanization":"","english":"watermelon"},
    {"thai":"กอง","romanization":"","english":"pile, stack"},
    {"thai":"จอง","romanization":"","english":"to book (reserve)"},
    {"thai":"ดอง","romanization":"","english":"fermented, pickled"},
    {"thai":"ตอน","romanization":"","english":"part, section (referring to a time period)"},
    {"thai":"ตอม","romanization":"","english":"to swarm"},
    {"thai":"เกิน","romanization":"","english":"over, go beyond"},
    {"thai":"เกิไปน","romanization":"","english":"excessively, too much"},
    {"thai":"เดิน","romanization":"","english":"to walk"},
    {"thai":"เติม","romanization":"","english":"to add, to fill"},
    {"thai":"ใบเตย","romanization":"","english":"Pandanus leaf"},
    {"thai":"เดียว","romanization":"","english":"only, sole"},
    {"thai":"เตียง","romanization":"","english":"bed"},
    {"thai":"เอียง","romanization":"","english":"tilted, inclined"},
    {"thai":"เดือน","romanization":"","english":"month"},
    {"thai":"เตือน","romanization":"","english":"to remind, to warn"},
    {"thai":"จวน","romanization":"","english":"nearly, almost"},
    {"thai":"ดวง","romanization":"","english":"fate, destiny"},
    {"thai":"ดูดวง","romanization":"","english":"to foretell, prophesy"},
    {"thai":"ตวง","romanization":"","english":"to measure, estimate"},
    {"thai":"บวม","romanization":"","english":"swollen"},
    {"thai":"เดือนเมษา","romanization":"","english":"April (month)"},
    {"thai":"เดือนมีนา","romanization":"","english":"March (month)"}
]
