[
    {"thai":"งา","romanization":"ngaa","english":"ivory, sesame, tusk"},
    {"thai":"นา","romanization":"naa","english":"rice field"},
    {"thai":"พา","romanization":"paa","english":"to bring, to lead (a person, animal)"},
    {"thai":"มา","romanization":"maa","english":"to come"},
    {"thai":"ยา","romanization":"yaa","english":"medicine, pill"},
    {"thai":"รา","romanization":"raa","english":"fungus"},
    {"thai":"ลา","romanization":"laa","english":"donkey"},
    {"thai":"แม่ชี","romanization":"","english":"nun"},
    {"thai":"มี","romanization":"mii","english":"to have"},
    {"thai":"คือ","romanization":"","english":"to be (as follows)"},
    {"thai":"คู","romanization":"","english":"small canal"},
    {"thai":"งู","romanization":"","english":"snake"},
    {"thai":"ชู","romanization":"","english":"raise up high"},
    {"thai":"ฟุ","romanization":"","english":"to be fluffy"},
    {"thai":"รู","romanization":"","english":"hole"},
    {"thai":"เท","romanization":"","english":"to pour"},
    {"thai":"แพ","romanization":"","english":"raft"},
    {"thai":"โค","romanization":"","english":"cow, bull, ox"},
    {"thai":"คอ","romanization":"","english":"neck"},
    {"thai":"พอ","romanization":"","english":"to be enough"},
    {"thai":"รอ","romanization":"","english":"to wait"},
    {"thai":"เรอ","romanization":"","english":"to burp"},
    {"thai":"เมีย","romanization":"","english":"wife (impolite term)"},
    {"thai":"เลีย","romanization":"","english":"seek favors, lick"},
    {"thai":"เรือ","romanization":"","english":"boat"},
    {"thai":"วัว","romanization":"","english":"cow, bull, bullock"},
    {"thai":"เรา","romanization":"","english":"we, us"},
    {"thai":"ไฟ","romanization":"","english":"fire, light"},
    {"thai":"ไทย","romanization":"","english":"Thai"},
    {"thai":"ใน","romanization":"","english":"in"},
    {"thai":"คำ","romanization":"","english":"word"},
    {"thai":"เงา","romanization":"","english":"shadow"},
    {"thai":"ไง","romanization":"","english":"What's up?"},
    {"thai":"ไว","romanization":"","english":"quick, fast"},
    {"thai":"นำนำ","romanization":"","english":"introduction"},
    {"thai":"เวลา","romanization":"","english":"time, when"},
    {"thai":"กำมือ","romanization":"","english":"handful"},
    {"thai":"แบมือ","romanization":"","english":"to hold out one's hand"},
    {"thai":"เปียโน","romanization":"","english":"piano"},
    {"thai":"ดารา","romanization":"","english":"celebrity"},
    {"thai":"พอใจ","romanization":"","english":"to be satisfied, pleased"},
    {"thai":"เรือใบ","romanization":"","english":"sailboat"},
    {"thai":"มือถือ","romanization":"","english":"cellphone"},
    {"thai":"ภาษา","romanization":"","english":"language"},
    {"thai":"ภาษี","romanization":"","english":"tax"},
    {"thai":"มาเลเซีย","romanization":"","english":"Malaysia"},
    {"thai":"ทำไม","romanization":"","english":"why"},
    {"thai":"สีเทา","romanization":"","english":"grey"},
    {"thai":"เมา","romanization":"","english":"to be drunk"}
]
