[
    {"thai":"สัปดาห์","romanization":"sàp-daa","english":"week"},
    {"thai":"ปี","romanization":"bpii","english":"year"},
    {"thai":"วันนี้","romanization":"wan-níi","english":"today"},
    {"thai":"พรุ่งนี้","romanization":"phrûng-níi","english":"tomorrow"},
    {"thai":"เมื่อวาน","romanization":"mûuea-waan","english":"yesterday"},
    {"thai":"ปฏิทิน","romanization":"bpà-dtì-thin","english":"calendar"},
    {"thai":"วินาที","romanization":"wí-naa-thii","english":"second"},
    {"thai":"ชั่วโมง","romanization":"chûua-moong","english":"hour"},
    {"thai":"นาที","romanization":"naa-thii","english":"minute"},
    {"thai":"นาฬิกา","romanization":"naa-lí-gaa","english":"clock"},
    {"thai":"วันจันทร์","romanization":"wan jan","english":"Monday"},
    {"thai":"วันอังคาร","romanization":"wan ang-khaan","english":"Tuesday"},
    {"thai":"วันพุธ","romanization":"wan phút","english":"Wednesday"},
    {"thai":"วันพฤหัสบดี","romanization":"wan phá-rúe-hàt-sà-baaw-dii","english":"Thursday"},
    {"thai":"วันศุกร์","romanization":"wan sùk","english":"Friday"},
    {"thai":"วันเสาร์","romanization":"wan sǎo","english":"Saturday"},
    {"thai":"วันอาทิตย์","romanization":"wan aa-thít","english":"Sunday"},
    {"thai":"เดือนพฤษภาคม","romanization":"duuean phrúet-sà-phaa-khom","english":"May"},
    {"thai":"เดือนมกราคม","romanization":"duuean má-gà-raa-khom","english":"January"},
    {"thai":"เดือนกุมภาพันธ์","romanization":"duuean gum-phaa-phan","english":"February"},
    {"thai":"เดือนมีนาคม","romanization":"duuean mii-naa-khom","english":"March"},
    {"thai":"เดือนเมษายน","romanization":"duuean mee-sǎ-yon","english":"April"},
    {"thai":"เดือนมิถุนายน","romanization":"duuean mí-thù-naa-yon","english":"June"},
    {"thai":"เดือนกรกฎาคม","romanization":"duuean gà-rá-gà-daa-khom","english":"July"},
    {"thai":"เดือนสิงหาคม","romanization":"duuean sǐng-hǎa-khom","english":"August"},
    {"thai":"เดือนกันยายน","romanization":"duuean gan-yaa-yon","english":"September"},
    {"thai":"เดือนตุลาคม","romanization":"duuean dtù-laa-khom","english":"October"},
    {"thai":"เดือนพฤศจิกายน","romanization":"duuean phrúet-sà-jì-gaa-yon","english":"November"},
    {"thai":"เดือนธันวาคม","romanization":"duuean than-waa-khom","english":"December"}
]
